### PR TITLE
Allow pass other options on assign fid

### PR DESCRIPTION
**Pull request by vitalybaev**
One important option for me (and others) is to pass some additional options when assign fid, like replication, collection or data center.

What do you think about this solution?

### CODE REVIEW

**Comment by tystuyfzand** [comment]
Looks like a reasonable solution. If you could add new lines after the array initializer, and ensure there is a blank line between each if statement, I'll merge it in.

**Comment by tystuyfzand** [comment]
Just a single line between declaration and the first if, other than that good to go!

**Comment by vitalybaev** [comment]
I've embarrassed with you word "lineS"

**Comment by tystuyfzand** [comment]
All good, thanks for the contribution!

**Pull request merged**
